[package]
name = "programming-bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
num-bigint = "0.4.6"
num-traits = "0.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench_sekp"
harness = false
